# frozen_string_literal: true

Vagrant.configure(2) do |config|
  # Configure The Box
  config.vm.box = 'bento/ubuntu-16.04'
  config.vm.hostname = 'ruby19'

  # Don't Replace The Default Key https://github.com/mitchellh/vagrant/pull/4707
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = config.vm.hostname
    v.memory = 2048
    v.cpus = 4
    v.customize [
      'modifyvm', :id,
      '--nictype1', 'virtio',
      '--name', config.vm.hostname,
      '--natdnshostresolver1', 'on'
    ]
  end

  config.vagrant.plugins = ['vagrant-vbguest']

  config.vm.synced_folder './', '/vagrant', disabled: true

  # Run The Base Provisioning Script
  config.vm.provision 'shell', path: './provision.sh'
end
